services:
  medis:
    image: ghcr.io/raw-network/medis:latest
    container_name: medis
    ports:
      - 3000:3000
    volumes:
      - ./videos:/usr/src/app/videos
    environment:
      - TZ=Asia/Makassar
    restart: unless-stopped
